# Generated by Django 3.1.3 on 2020-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
